-- Create landmarks table
CREATE TABLE IF NOT EXISTS public.landmarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    name_local text,
    cat text DEFAULT 'อื่นๆ'::text,
    icon text DEFAULT '📍'::text,
    city_id text NOT NULL,
    address text,
    lat numeric,
    lng numeric,
    description text,
    duration_min integer DEFAULT 90,
    fee text,
    transport jsonb DEFAULT '[]'::jsonb,
    cover_image text,
    names jsonb DEFAULT '{}'::jsonb,
    descriptions jsonb DEFAULT '{}'::jsonb,
    status text DEFAULT 'approved'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.landmarks ENABLE ROW LEVEL SECURITY;

-- Create Policy to allow read access for everyone
CREATE POLICY "Allow public read access" ON public.landmarks
    FOR SELECT USING (status = 'approved');

-- Create Policy to allow anonymous insert (e.g. users proposing places)
CREATE POLICY "Allow public inserts" ON public.landmarks
    FOR INSERT WITH CHECK (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_landmarks_city_status ON public.landmarks(city_id, status);

-- Seed Data: Bangkok
INSERT INTO public.landmarks (name, name_local, cat, icon, city_id, address, lat, lng, description, duration_min, fee, transport, names, descriptions, status)
VALUES
('วัดพระศรีรัตนศาสดาราม (วัดพระแก้ว)', 'วัดพระแก้ว', 'วัด', '🛕', 'bkk', 'ถนนหน้าพระลาน แขวงพระบรมมหาราชวัง เขตพระนคร กรุงเทพมหานคร 10200', 13.7516, 100.4927, 'วัดหลวงที่สำคัญที่สุดของประเทศไทย เป็นที่ประดิษฐานพระพุทธมหามณีรัตนปฏิมากร (พระแก้วมรกต)', 120, 'คนไทยฟรี / ต่างชาติ 500 บาท', '[{"i":"🚇", "t":"MRT สนามไชย ทางออก 1 แล้วเดินต่อ 15 นาที หรือนั่งเรือด่วนเจ้าพระยาลงท่าช้าง"}]'::jsonb, '{"th":"วัดพระศรีรัตนศาสดาราม (วัดพระแก้ว)", "en":"Wat Phra Kaew (Temple of the Emerald Buddha)", "ja":"ワット・プラแก้ว"}'::jsonb, '{"th":"วัดคู่บ้านคู่เมืองและพระบรมมหาราชวังของไทย", "en":"Thailand''s most sacred Buddhist temple housing the Emerald Buddha."}'::jsonb, 'approved'),
('พระบรมมหาราชวัง', 'พระบรมมหาราชวัง', 'พระราชวัง', '🏰', 'bkk', 'ถนนหน้าพระลาน แขวงพระบรมมหาราชวัง เขตพระนคร กรุงเทพมหานคร 10200', 13.7500, 100.4913, 'อดีตที่ประทับอย่างเป็นทางการของกษัตริย์สยาม ปัจจุบันใช้ในการประกอบพระราชพิธีสำคัญ', 120, 'คนไทยฟรี / ต่างชาติ 500 บาท (ตั๋วรวมกับวัดพระแก้ว)', '[{"i":"🚗", "t":"รถแท็กซี่ หรือ เรือด่วนเจ้าพระยาลงท่าช้าง"}]'::jsonb, '{"th":"พระบรมมหาราชวัง", "en":"The Grand Palace"}'::jsonb, '{"th":"พระราชวังโบราณอันวิจิตรงดงาม", "en":"A complex of buildings at the heart of Bangkok."}'::jsonb, 'approved'),
('วัดอรุณราชวรารามราชวรมหาวิหาร', 'วัดอรุณ', 'วัด', '🛕', 'bkk', '34 ถนนอรุณอมรินทร์ แขวงวัดอรุณ เขตบางกอกใหญ่ กรุงเทพมหานคร 10600', 13.7437, 100.4889, 'วัดโบราณริมแม่น้ำเจ้าพระยาที่โดดเด่นด้วยพระปรางค์ประดับกระเบื้องเคลือบโบราณอย่างงดงาม', 90, 'คนไทยฟรี / ต่างชาติ 100 บาท', '[{"i":"🛳", "t":"นั่งเรือข้ามฟากจากท่าเตียนไปยังท่าวัดอรุณ"}]'::jsonb, '{"th":"วัดอรุณราชวรารามราชวรมหาวิหาร", "en":"Wat Arun (Temple of Dawn)"}'::jsonb, '{"th":"วัดริมน้ำพระปรางค์สีขาวงดงาม", "en":"Famous riverside temple known for its central prang tower."}'::jsonb, 'approved'),
('ตลาดนัดจตุจักร', 'สวนจตุจักร', 'ช้อปปิ้ง', '🛍', 'bkk', 'ถนนกำแพงเพชร 2 แขวงจตุจักร เขตจตุจักร กรุงเทพมหานคร 10900', 13.7999, 100.5508, 'ตลาดนัดวันหยุดที่ใหญ่ที่สุดในประเทศไทย แหล่งรวมสินค้านานาชนิดตั้งแต่เสื้อผ้าไปจนถึงของแต่งบ้าน', 180, 'ฟรี', '[{"i":"🚇", "t":"BTS สถานีหมอชิต หรือ MRT สถานีสวนจตุจักร"}]'::jsonb, '{"th":"ตลาดนัดจตุจักร", "en":"Chatuchak Weekend Market"}'::jsonb, '{"th":"ช้อปปิ้งตลาดนัดวันหยุดขนาดใหญ่", "en":"The largest weekend market in Thailand."}'::jsonb, 'approved');

-- Seed Data: Seoul
INSERT INTO public.landmarks (name, cat, icon, city_id, address, lat, lng, description, duration_min, fee, transport, names, descriptions, status)
VALUES
('Gyeongbokgung Palace', 'พระราชวัง', '🏯', 'sel', '161 Sajik-ro, Jongno-gu, Seoul', 37.5796, 126.9770, 'The main royal palace of the Joseon dynasty, built in 1395.', 120, '₩3,000 / Free if wearing Hanbok', '[{"i":"🚇", "t":"Subway Line 3 Gyeongbokgung Station Exit 5"}]'::jsonb, '{"th":"พระราชวังเคียงบก", "en":"Gyeongbokgung Palace", "ko":"경복궁"}'::jsonb, '{"th":"พระราชวังหลวงที่ใหญ่ที่สุดในโซล", "en":"The largest of the Five Grand Palaces built during the Joseon Dynasty."}'::jsonb, 'approved'),
('Bukchon Hanok Village', 'ย่าน', '🏡', 'sel', '37 Gyeedong-gil, Jongno-gu, Seoul', 37.5826, 126.9836, 'A traditional village containing hundreds of hanoks (Korean traditional houses).', 90, 'Free', '[{"i":"🚇", "t":"Subway Line 3 Anguk Station Exit 2"}]'::jsonb, '{"th":"หมู่บ้านโบราณบุคชอนฮานอก", "en":"Bukchon Hanok Village", "ko":"북촌한옥마을"}'::jsonb, '{"th":"หมู่บ้านเกาหลีโบราณอายุกว่า 600 ปี", "en":"A historic village preserved to show a 600-year-old urban environment."}'::jsonb, 'approved'),
('N Seoul Tower', 'วิวทิวทัศน์', '🗼', 'sel', '105 Namsangongwon-gil, Yongsan-gu, Seoul', 37.5512, 126.9882, 'A communication and observation tower located on Namsan Mountain.', 120, '₩16,000 (Observatory)', '[{"i":"🚇", "t":"Namsan Cable Car or Namsan Sunhwan Shuttle Bus No. 01"}]'::jsonb, '{"th":"โซลทาวเวอร์", "en":"N Seoul Tower", "ko":"N서울타워"}'::jsonb, '{"th":"จุดชมวิวเมืองโซลยอดนิยมบนภูเขานัมซาน", "en":"Iconic landmark offering panoramic views of Seoul."}'::jsonb, 'approved');

-- Create itineraries table
CREATE TABLE IF NOT EXISTS public.itineraries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    city_id text NOT NULL,
    country_id text NOT NULL,
    start_date date,
    end_date date,
    start_time text DEFAULT '09:00',
    hotel text,
    n_days integer DEFAULT 3,
    itin jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for itineraries
ALTER TABLE public.itineraries ENABLE ROW LEVEL SECURITY;

-- Create Policies for itineraries
CREATE POLICY "Allow individual read access" ON public.itineraries
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow individual insert access" ON public.itineraries
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow individual update access" ON public.itineraries
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow individual delete access" ON public.itineraries
    FOR DELETE USING (auth.uid() = user_id);

